services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django-web
    depends_on:
      - db
    volumes:
      # Mount your project source code (for dev)
      - ./bcs:/app
      # Keep static files separate if needed
      - ./static:/app/staticfiles
    env_file:
      - .env
    command: /app/entrypoint.prod.sh  # or "python manage.py runserver 0.0.0.0:8000" for dev
    ports:
      - "8000:8000"

  nginx-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web

volumes:
  postgres_data:
